In [ ]:
)#welcome to numpy
import numpy as np
scores = np.array([45, 67, 89, 34, 72, 90, 55])
print(scores)
print(type(scores))
arr=np.array(42)

print(arr)
arr=np.ones(8)
print(arr)
print(np.__version__)



[45 67 89 34 72 90 55]
<class 'numpy.ndarray'>
42
[1. 1. 1. 1. 1. 1. 1. 1.]
2.1.3


array([1])

In [32]:
np.arange(1,4,3)

array([1])

In [34]:
arr = np.array([[1,2,3],[4,5,6]])

arr.shape   # (2,3)
   # data type


(2, 3)

In [35]:
arr.ndim    # 2  (dimensions)


2

In [36]:
arr.size    # total elements


6

In [37]:
arr.dtype

dtype('int64')

In [72]:
#array indexing 1D array
marks=np.array([34,45,67,89,77])

marks[marks>10]+=5
print(marks)
print((marks>40) & (marks<70))
print(marks[(marks>40) & (marks<70)])

[39 50 72 94 82]
[False  True False False False]
[50]


In [62]:
#2D array indexing and slicing
import numpy as np
numbers=np.array([[34,56,67],[23,56,43]])

print(numbers[0,2])
print(numbers[:2])

67
[[34 56 67]
 [23 56 43]]


In [74]:
salary = np.array([20000,35000,50000,80000,120000])
#Find salaries between 30k and 80k
#FInd saalaries above 100k
print(salary[(salary>30000)&(salary<120000)])
print(salary[salary>100000])

[35000 50000 80000]
[120000]


In [6]:
import numpy as np
array=np.array([1,2,3,4,5])
print(array)
array =array *2
print(array)
print(type(array))
print(np.__version__)
print(np.amax)

[1 2 3 4 5]
[ 2  4  6  8 10]
<class 'numpy.ndarray'>
2.1.3
<function amax at 0x000001A9F5B95620>


In [19]:
#multidimensionall 2d array
import numpy as np
ar=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

print(ar[:,1])

[2 5 8]


In [22]:
#arithmetic scalar 
import numpy as np
array=np.array([1,2,3,4])
print(array +1)
print(array-1)
print(array * 2)
print(array /4)
print(array ** 5)

[2 3 4 5]
[0 1 2 3]
[2 4 6 8]
[0.25 0.5  0.75 1.  ]
[   1   32  243 1024]


In [56]:
#vectorized math functions
import numpy as np
array=np.array([1,2,3,4])
print(np.sqrt(array))
print(np.round(array))
print(np.ceil(array))
print(np.floor(array))
print(np.amax(array))
print(np.amin(array))
print(np.absolute(array))
print(np.average(array))
print(np.std(array))
print(np.mean(array))
print(np.sum(array))
print(np.argmin(array))
print(np.argmax(array))
print(np.sum(array,axis=0))

[1.         1.41421356 1.73205081 2.        ]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
4
1
[1 2 3 4]
2.5
1.118033988749895
2.5
10
0
3
10


In [39]:
#elemet wise arithmetic
import numpy as np
a=np.array([2,4,6])
b=np.array([1,3,5])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[ 3  7 11]
[1 1 1]
[ 2 12 30]
[2.         1.33333333 1.2       ]
[   2   64 7776]


In [70]:
#comparison operators
scores=np.array([60,55,78,90,100])

passed=scores[(scores>=60) &(scores<80)]
A=scores[(scores>=80) &(scores<100)]
print(passed)
print(A)

[60 78]
[90]
